// WebAssembly compression module
// This module provides compress/decompress functions using WebAssembly compiled from Rust
// The Rust code uses the flate2 crate for high-performance gzip compression

// Import the Wasm module generated by wasm-pack
// If the Wasm build hasn't been completed yet, you'll need to run: npm run build:wasm
import init, { compress as wasmCompress, decompress as wasmDecompress } from '../pkg/wasm_compressor.js';

// Export the init function to initialize the Wasm module
export default init;

// Wrap the Wasm functions to match our application's interface
export const compress = (data: Uint8Array): Uint8Array => {
  const result = wasmCompress(data);
  return new Uint8Array(result);
};

export const decompress = (data: Uint8Array): Uint8Array => {
  const result = wasmDecompress(data);
  return new Uint8Array(result);
};
